In [1]:
import pandas as pd

In [2]:
import os
os.chdir(r"C:\Users\admin\demand-forecasting")
print(os.getcwd())

C:\Users\admin\demand-forecasting

In [3]:
sales = pd.read_csv("data/raw/sales_train_validation.csv")
calendar = pd.read_csv("data/raw/calendar.csv")
prices = pd.read_csv("data/raw/sell_prices.csv")

In [4]:
print(sales.shape, sales.columns[:10].to_list())
sales.head()

(30490, 1919) ['id', 'item_id', 'dept_id', 'cat_id', 'store_id', 'state_id', 'd_1', 'd_2', 'd_3', 'd_4']

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,...,d_1904,d_1905,d_1906,d_1907,d_1908,d_1909,d_1910,d_1911,d_1912,d_1913
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,3,0,1,1,1,3,0,1,1
1,HOBBIES_1_002_CA_1_validation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,HOBBIES_1_003_CA_1_validation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,1,2,1,1,1,0,1,1,1
3,HOBBIES_1_004_CA_1_validation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,0,5,4,1,0,1,3,7,2
4,HOBBIES_1_005_CA_1_validation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,1,1,0,1,1,2,2,2,4

In [5]:
print(calendar.shape, calendar.columns.to_list())
calendar.head()

(1969, 14) ['date', 'wm_yr_wk', 'weekday', 'wday', 'month', 'year', 'd', 'event_name_1', 'event_type_1', 'event_name_2', 'event_type_2', 'snap_CA', 'snap_TX', 'snap_WI']

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
0,2011-01-29,11101,Saturday,1,1,2011,d_1,NaN,NaN,NaN,NaN,0,0,0
1,2011-01-30,11101,Sunday,2,1,2011,d_2,NaN,NaN,NaN,NaN,0,0,0
2,2011-01-31,11101,Monday,3,1,2011,d_3,NaN,NaN,NaN,NaN,0,0,0
3,2011-02-01,11101,Tuesday,4,2,2011,d_4,NaN,NaN,NaN,NaN,1,1,0
4,2011-02-02,11101,Wednesday,5,2,2011,d_5,NaN,NaN,NaN,NaN,1,0,1

In [6]:
print(prices.shape, prices.columns.to_list())
prices.head()

(6841121, 4) ['store_id', 'item_id', 'wm_yr_wk', 'sell_price']

  store_id        item_id  wm_yr_wk  sell_price
0     CA_1  HOBBIES_1_001     11325        9.58
1     CA_1  HOBBIES_1_001     11326        9.58
2     CA_1  HOBBIES_1_001     11327        8.26
3     CA_1  HOBBIES_1_001     11328        8.26
4     CA_1  HOBBIES_1_001     11329        8.26

In [7]:
item = sales[['item_id', 'dept_id', 'cat_id']].drop_duplicates()

store = sales[['store_id', 'state_id']].drop_duplicates()

In [8]:
item.head()

         item_id    dept_id   cat_id
0  HOBBIES_1_001  HOBBIES_1  HOBBIES
1  HOBBIES_1_002  HOBBIES_1  HOBBIES
2  HOBBIES_1_003  HOBBIES_1  HOBBIES
3  HOBBIES_1_004  HOBBIES_1  HOBBIES
4  HOBBIES_1_005  HOBBIES_1  HOBBIES

In [ ]:
dim_date = calendar[['date','d','weekday']].copy()
dim_date['is_weekend'] = [1 if c == 1 or c == 2 else 0 for c in calendar['wday']]
dim_date['is_holiday'] = [1 if pd.notna(c) else 0 for c in calendar['event_name_1']]
dim_date.rename(columns={
    'date':'la_date',
    'd':'date_id',
    'weekday':'jour_de_semaine'
},inplace=True)

print(dim_date.shape)
print(dim_date.head())

(1969, 5)
      la_date date_id jour_de_semaine  is_weekend  is_holiday
0  2011-01-29     d_1        Saturday           1           0
1  2011-01-30     d_2          Sunday           1           0
2  2011-01-31     d_3          Monday           0           0
3  2011-02-01     d_4         Tuesday           0           0
4  2011-02-02     d_5       Wednesday           0           0

In [10]:
c_from = calendar[['date','wm_yr_wk']].drop_duplicates(subset="wm_yr_wk")
c_from.rename(columns={
    'date':'valid_from'
},inplace=True)

c_to = calendar[['date','wm_yr_wk']].drop_duplicates(subset="wm_yr_wk")
c_to['date'] = c_to['date'].shift(-1)
c_to.rename(columns={
    'date':'valid_to'
},inplace=True)

price = prices.merge(c_from, on='wm_yr_wk', how='left')
price = price.merge(c_to, on='wm_yr_wk', how='left')

price = price.drop(columns=['wm_yr_wk'])

price = price.rename(columns={'sell_price': 'price'})

print(price.shape)
print(price.head())
print(price.isna().sum())

(6841121, 5)
  store_id        item_id  price  valid_from    valid_to
0     CA_1  HOBBIES_1_001   9.58  2013-07-13  2013-07-20
1     CA_1  HOBBIES_1_001   9.58  2013-07-20  2013-07-27
2     CA_1  HOBBIES_1_001   8.26  2013-07-27  2013-08-03
3     CA_1  HOBBIES_1_001   8.26  2013-08-03  2013-08-10
4     CA_1  HOBBIES_1_001   8.26  2013-08-10  2013-08-17
store_id          0
item_id           0
price             0
valid_from        0
valid_to      30490
dtype: int64

In [11]:
fact_sales = sales.melt(
    id_vars=['item_id', 'store_id'],
    value_vars=[col for col in sales.columns if col.startswith('d_')],
    var_name='date_id',
    value_name='quantite'
)

print(fact_sales.shape)
print(fact_sales.head())

(58327370, 4)
         item_id store_id date_id  quantite
0  HOBBIES_1_001     CA_1     d_1         0
1  HOBBIES_1_002     CA_1     d_1         0
2  HOBBIES_1_003     CA_1     d_1         0
3  HOBBIES_1_004     CA_1     d_1         0
4  HOBBIES_1_005     CA_1     d_1         0

In [12]:
fact_sales = fact_sales.merge(dim_date, on='date_id', how='left')

In [13]:
fact_sales.head()
# print(fact_sales.shape)
# print(fact_sales.isna().sum())

,item_id,store_id,date_id,quantite,la_date,jour_de_semaine,is_weekend,is_holiday
0,HOBBIES_1_001,CA_1,d_1,0,2011-01-29,Saturday,1,0
1,HOBBIES_1_002,CA_1,d_1,0,2011-01-29,Saturday,1,0
2,HOBBIES_1_003,CA_1,d_1,0,2011-01-29,Saturday,1,0
3,HOBBIES_1_004,CA_1,d_1,0,2011-01-29,Saturday,1,0
4,HOBBIES_1_005,CA_1,d_1,0,2011-01-29,Saturday,1,0

In [14]:
item = item.reset_index(drop=True)
item['id'] = item.index + 1

store = store.reset_index(drop=True)
store['id'] = store.index + 1

dim_date = dim_date.reset_index(drop=True)
dim_date['id'] = dim_date.index + 1

In [15]:
print(item[['item_id', 'id']].head())
print(store[['store_id', 'id']].head())
print(dim_date[['date_id', 'id']].head())

         item_id  id
0  HOBBIES_1_001   1
1  HOBBIES_1_002   2
2  HOBBIES_1_003   3
3  HOBBIES_1_004   4
4  HOBBIES_1_005   5
  store_id  id
0     CA_1   1
1     CA_2   2
2     CA_3   3
3     CA_4   4
4     TX_1   5
  date_id  id
0     d_1   1
1     d_2   2
2     d_3   3
3     d_4   4
4     d_5   5

In [16]:
mapping_item = item.set_index("item_id")['id']
price['item_id'] = price['item_id'].map(mapping_item)

mapping_store = store.set_index("store_id")['id']
price['store_id'] = price['store_id'].map(mapping_store)

print(price[['item_id', 'store_id']].head())
print(price.isna().sum())

   item_id  store_id
0        1         1
1        1         1
2        1         1
3        1         1
4        1         1
store_id          0
item_id           0
price             0
valid_from        0
valid_to      30490
dtype: int64

In [17]:
fact_sales['item_id'] = fact_sales['item_id'].map(mapping_item)

fact_sales['store_id'] = fact_sales['store_id'].map(mapping_store)

mapping_date = dim_date.set_index('date_id')['id']
fact_sales['date_id'] = fact_sales['date_id'].map(mapping_date)

fact_sales = fact_sales.drop(columns=['la_date', 'jour_de_semaine', 'is_weekend', 'is_holiday'])

In [18]:
print(fact_sales.shape)
print(fact_sales.head())
print(fact_sales.isna().sum())

(58327370, 4)
   item_id  store_id  date_id  quantite
0        1         1        1         0
1        2         1        1         0
2        3         1        1         0
3        4         1        1         0
4        5         1        1         0
item_id     0
store_id    0
date_id     0
quantite    0
dtype: int64

In [19]:
item = item.rename(columns={'cat_id': 'categorie', 'dept_id': 'departement'})
store = store.rename(columns={'state_id': 'etat'})

In [20]:
dim_date['is_weekend'] = dim_date['is_weekend'].astype(bool)
dim_date['is_holiday'] = dim_date['is_holiday'].astype(bool)

In [21]:
from sqlalchemy import create_engine

engine = create_engine("postgresql://forecaster:forecaster_pass@localhost:5432/demand_db")

In [22]:
# item.to_sql('item', engine, if_exists='append', index=False)
# store.to_sql('store', engine, if_exists='append', index=False)
# dim_date.to_sql('dim_date', engine, if_exists='append', index=False)

In [23]:
import io

def fast_load(df, table_name, engine):
    buffer = io.StringIO()
    df.to_csv(buffer, index=False, header=False)
    buffer.seek(0)
    
    raw_conn = engine.raw_connection()
    cursor = raw_conn.cursor()
    cursor.copy_expert(
        f"COPY {table_name} ({', '.join(df.columns)}) FROM STDIN WITH CSV",
        buffer
    )
    raw_conn.commit()
    cursor.close()
    raw_conn.close()

In [24]:
# fast_load(price, 'price', engine)

In [25]:
import io

def fast_load_chunked(df, table_name, engine, chunk_size=1_000_000):
    total = len(df)
    for start in range(0, total, chunk_size):
        end = min(start + chunk_size, total)
        chunk = df.iloc[start:end]
        
        buffer = io.StringIO()
        chunk.to_csv(buffer, index=False, header=False)
        buffer.seek(0)
        
        raw_conn = engine.raw_connection()
        cursor = raw_conn.cursor()
        cursor.copy_expert(
            f"COPY {table_name} ({', '.join(chunk.columns)}) FROM STDIN WITH CSV",
            buffer
        )
        raw_conn.commit()
        cursor.close()
        raw_conn.close()
        
        print(f"Chargé {end}/{total} lignes")

fast_load_chunked(fact_sales, 'fact_sales', engine)

Chargé 1000000/58327370 lignes
Chargé 2000000/58327370 lignes
Chargé 3000000/58327370 lignes
Chargé 4000000/58327370 lignes
Chargé 5000000/58327370 lignes
Chargé 6000000/58327370 lignes
Chargé 7000000/58327370 lignes
Chargé 8000000/58327370 lignes
Chargé 9000000/58327370 lignes
Chargé 10000000/58327370 lignes
Chargé 11000000/58327370 lignes
Chargé 12000000/58327370 lignes
Chargé 13000000/58327370 lignes
Chargé 14000000/58327370 lignes
Chargé 15000000/58327370 lignes
Chargé 16000000/58327370 lignes
Chargé 17000000/58327370 lignes
Chargé 18000000/58327370 lignes
Chargé 19000000/58327370 lignes
Chargé 20000000/58327370 lignes
Chargé 21000000/58327370 lignes
Chargé 22000000/58327370 lignes
Chargé 23000000/58327370 lignes
Chargé 24000000/58327370 lignes
Chargé 25000000/58327370 lignes
Chargé 26000000/58327370 lignes
Chargé 27000000/58327370 lignes
Chargé 28000000/58327370 lignes
Chargé 29000000/58327370 lignes
Chargé 30000000/58327370 lignes
Chargé 31000000/58327370 lignes
Chargé 32000000/58327370 lignes
Chargé 33000000/58327370 lignes
Chargé 34000000/58327370 lignes
Chargé 35000000/58327370 lignes
Chargé 36000000/58327370 lignes
Chargé 37000000/58327370 lignes
Chargé 38000000/58327370 lignes
Chargé 39000000/58327370 lignes
Chargé 40000000/58327370 lignes
Chargé 41000000/58327370 lignes
Chargé 42000000/58327370 lignes
Chargé 43000000/58327370 lignes
Chargé 44000000/58327370 lignes
Chargé 45000000/58327370 lignes
Chargé 46000000/58327370 lignes
Chargé 47000000/58327370 lignes
Chargé 48000000/58327370 lignes
Chargé 49000000/58327370 lignes
Chargé 50000000/58327370 lignes
Chargé 51000000/58327370 lignes
Chargé 52000000/58327370 lignes
Chargé 53000000/58327370 lignes
Chargé 54000000/58327370 lignes
Chargé 55000000/58327370 lignes
Chargé 56000000/58327370 lignes
Chargé 57000000/58327370 lignes
Chargé 58000000/58327370 lignes
Chargé 58327370/58327370 lignes